### ISSUE TITLE
Failure when using two part TLDs (namecheap)

### ISSUE THREAD

**Issue by snk-nick** [Bemmu/PyNamecheap#25]
Authentication fails to namecheap when trying to use any .net.au or .com.au TLD. Using .com or .net domains under same account with same code work no issues.

`Hook command "/etc/letsencrypt/scripts/lexicon-namecheap.sh create" returned error code 255
Error output from lexicon-namecheap.sh:
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/lexicon/cli.py", line 117, in main
    results = client.execute()
  File "/usr/local/lib/python3.5/dist-packages/lexicon/client.py", line 71, in execute
    return self.provider.create_record(record_type, name, content)
  File "/usr/local/lib/python3.5/dist-packages/lexicon/providers/base.py", line 80, in create_record
    return self._create_record(rtype, name, content)
  File "/usr/local/lib/python3.5/dist-packages/lexicon/providers/namecheap.py", line 201, in _create_record
    self.client.domains_dns_addHost(self.domain, record)
  File "/usr/local/lib/python3.5/dist-packages/namecheap.py", line 373, in domains_dns_addHost
    host_records_remote = self.domains_dns_getHosts(domain)
  File "/usr/local/lib/python3.5/dist-packages/namecheap.py", line 346, in domains_dns_getHosts
    sld, tld = domain.split(".")
ValueError: too many values to unpack (expected 2)`

**Comment by simonmcnair** [comment]
I'm having this too with a .co.uk :-(
